debug: false
spring:
  application:
    name: author-service
server:
  port: 8100



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: swagger-ui.html